### ISSUE TITLE
tqdm auto

### ISSUE THREAD

**Issue by reouen** [summerstay/sentence-completions-gpt-2#3]
Error with python 2.7 and 3.82. I installed tqdm and tqdm through pip. Whats the issue?

`me@me:~/Desktop/sentence-completions-gpt-2$ python3 completion*
Traceback (most recent call last):
  File "completions_tree.py", line 9, in <module>
    from transformers import GPT2Tokenizer, GPT2LMHeadModel
  File "/home/me/.local/lib/python3.8/site-packages/transformers/__init__.py", line 23, in <module>
    from .configuration_albert import ALBERT_PRETRAINED_CONFIG_ARCHIVE_MAP, AlbertConfig
  File "/home/me/.local/lib/python3.8/site-packages/transformers/configuration_albert.py", line 18, in <module>
    from .configuration_utils import PretrainedConfig
  File "/home/me/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 25, in <module>
    from .file_utils import CONFIG_NAME, cached_path, hf_bucket_url, is_remote_url
  File "/home/me/.local/lib/python3.8/site-packages/transformers/file_utils.py", line 25, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'

me@me:~/Desktop/sentence-completions-gpt-2$ python2.7 complet*
  File "completions_tree.py", line 57
    logits, past = model(**inputs, past=past)   
                                 ^
`

**Comment by reouen** [comment]
tqdm --upgrade fixed
